# ruff: noqa: E501

scored_sections = [
    {
        "id": "scored",
        "weighting": 1.0,
        "name": "Scored",
        "sub_criteria": [
            {
                "id": "do-the-activities-being-pursued-by-a-place-fit-with-the-plan-for-neighbourhoods-programme-objectives",
                "name": "Do the activities being pursued by a place fit with the Plan for Neighbourhoods programme objectives?",
                "themes": [
                    {
                        "id": "would-you-like-to-upload-any-supporting-documents?",
                        "name": "Would you like to upload any supporting documents?",
                        "answers": [
                            {
                                "field_id": "yMWAhw",
                                "form_name": "10-year-vision",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Would you like to upload any supporting documents?",
                            },
                            {
                                "field_id": "QdfSRQ",
                                "form_name": "10-year-vision",
                                "field_type": "clientSideFileUploadField",
                                "presentation_type": "text",
                                "question": "Upload your 10-year vision.",
                            },
                            {
                                "field_id": "lVzOPc",
                                "form_name": "10-year-vision",
                                "field_type": "clientSideFileUploadField",
                                "presentation_type": "text",
                                "question": "Upload any supporting documents and provide a brief description of their purpose.",
                            },
                            {
                                "field_id": "HzWBci",
                                "form_name": "10-year-vision",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Specify the purpose for each document using the format: 'File name - purpose'. ",
                            },
                            {
                                "field_id": "SZrPXB",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about the local challenges you have identified as priorities to address in the first investment period and why.",
                            },
                            {
                                "field_id": "DOWpEu",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about any local opportunities for improvement or investment that you have identified and wish to pursue in the first investment period.",
                            },
                            {
                                "field_id": "XaZCkd",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about the local challenges you have identified as priorities to address in the first investment period and why.",
                            },
                            {
                                "field_id": "aJyHdS",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about any local opportunities for improvement or investment that you have identified and wish to pursue in the first investment period.",
                            },
                            {
                                "field_id": "PjdnJZ",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about the local challenges you have identified as priorities to address in the first investment period and why.",
                            },
                            {
                                "field_id": "AORTLp",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about any local opportunities for improvement or investment that you have identified and wish to pursue in the first investment period.",
                            },
                            {
                                "field_id": "WFRgIa",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which categories of pre-approved interventions do you plan to fund?",
                            },
                            {
                                "field_id": "UHWiHB",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which categories of pre-approved interventions do you plan to fund?",
                            },
                            {
                                "field_id": "DgNaHl",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does your Neighbourhood Board wish to deliver off-menu interventions?",
                            },
                            {
                                "field_id": "vUIIVo",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which interventions relating to 'Health and wellbeing' do you plan to fund in the first investment period?",
                            },
                            {
                                "field_id": "PtMucP",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Not sure which pre-approved interventions we plan to fund at this stage",
                            },
                            {
                                "field_id": "RAcQRK",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which interventions relating to 'Work, productivity and skills' do you plan to fund in the first investment period?",
                            },
                            {
                                "field_id": "paRpaG",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Not sure which pre-approved interventions we plan to fund at this stage",
                            },
                            {
                                "field_id": "xFBFbU",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which interventions relating to 'Cohesion' do you plan to fund in the first investment period?",
                            },
                            {
                                "field_id": "Vewypf",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Not sure which pre-approved interventions we plan to fund at this stage",
                            },
                            {
                                "field_id": "NwlpeY",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which interventions relating to 'Safety and security' do you plan to fund in the first investment period?",
                            },
                            {
                                "field_id": "qfojsS",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Not sure which pre-approved interventions we plan to fund at this stage",
                            },
                            {
                                "field_id": "RsMYwj",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which interventions relating to 'Transport' do you plan to fund in the first investment period?",
                            },
                            {
                                "field_id": "NqOcWG",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Not sure which pre-approved interventions we plan to fund at this stage",
                            },
                            {
                                "field_id": "cpsPOw",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Describe the proposed intervention.",
                            },
                            {
                                "field_id": "GrBsow",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which interventions relating to 'Regeneration, high streets and heritage' do you plan to fund in the first investment period?",
                            },
                            {
                                "field_id": "lcbdeK",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Not sure which pre-approved interventions we plan to fund at this stage",
                            },
                            {
                                "field_id": "EqLMxj",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which interventions relating to 'Housing' do you plan to fund in the first investment period?",
                            },
                            {
                                "field_id": "Itcjmg",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Not sure which pre-approved interventions we plan to fund at this stage",
                            },
                            {
                                "field_id": "AHJYFi",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which interventions relating to 'Education and opportunity' do you plan to fund in the first investment period?",
                            },
                            {
                                "field_id": "rAUhnm",
                                "form_name": "4-year-investment-plan:-interventions",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Not sure which pre-approved interventions we plan to fund at this stage",
                            },
                        ],
                    },
                ],
            },
            {
                "id": "does-the-place-have-a-credible-and-realistic-expenditure-forecast-fitting-with-the-funding-flexibility-rules",
                "name": "Does the place have a credible and realistic expenditure forecast, fitting with the funding flexibility rules?",
                "themes": [
                    {
                        "id": "does-the-place-have-a-credible-and-realistic-expenditure-forecast-fitting-with-the-funding-flexibility-rules",
                        "name": "Does the place have a credible and realistic expenditure forecast, fitting with the funding flexibility rules?",
                        "answers": [
                            {
                                "field_id": "aLeDKy",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us about any unknown uses of funding in the first investment period.",
                                    {
                                        "wajlvP": {
                                            "column_title": "Unknown uses of funding (2026-27)",
                                            "type": "numberField",
                                        },
                                        "bPbTEe": {
                                            "column_title": "Unknown uses of funding (2027-28)",
                                            "type": "numberField",
                                        },
                                        "XGBxKK": {
                                            "column_title": "Unknown uses of funding (2028-29)",
                                            "type": "numberField",
                                        },
                                        "fqmDlx": {
                                            "column_title": "Unknown uses of funding (2029-30)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "lREPmq",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for capacity funding throughout the programme.",
                                    {
                                        "kzCRNQ": {
                                            "column_title": "Capacity funding (2024-25)",
                                            "type": "numberField",
                                        },
                                        "hWffef": {
                                            "column_title": "Capacity funding (2025-26)",
                                            "type": "numberField",
                                        },
                                        "exKKtD": {
                                            "column_title": "Capacity funding (2026-27)",
                                            "type": "numberField",
                                        },
                                        "SWBFvn": {
                                            "column_title": "Capacity funding (2027-28)",
                                            "type": "numberField",
                                        },
                                        "mjXkxo": {
                                            "column_title": "Capacity funding (2028-29)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "lREPmq",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "",
                                    {
                                        "jhEJRB": {
                                            "column_title": "Capacity funding (2029-30)",
                                            "type": "numberField",
                                        },
                                        "IlUUxg": {
                                            "column_title": "Capacity funding (2030-31)",
                                            "type": "numberField",
                                        },
                                        "nZFwqm": {
                                            "column_title": "Capacity funding (2031-32)",
                                            "type": "numberField",
                                        },
                                        "rQUbSC": {
                                            "column_title": "Capacity funding (2033-34)",
                                            "type": "numberField",
                                        },
                                        "GCnfMS": {
                                            "column_title": "Capacity funding (2034-25)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "aUQnBP",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for management costs in the first investment period.",
                                    {
                                        "QVuIFv": {"column_title": "Management costs (2026-27)", "type": "numberField"},
                                        "GHFRTw": {"column_title": "Management costs (2027-28)", "type": "numberField"},
                                        "sAelLv": {"column_title": "Management costs (2028-29)", "type": "numberField"},
                                        "ZvlDXd": {"column_title": "Management costs (2029-30)", "type": "numberField"},
                                    },
                                ],
                            },
                            {
                                "field_id": "QEywSA",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for any off-menu interventions in the first investment period.",
                                    {
                                        "NCgxYf": {
                                            "column_title": "Off-menu interventions (2026-27)",
                                            "type": "numberField",
                                        },
                                        "afjufs": {
                                            "column_title": "Off-menu interventions (2027-28)",
                                            "type": "numberField",
                                        },
                                        "EbZeKz": {
                                            "column_title": "Off-menu interventions (2028-29)",
                                            "type": "numberField",
                                        },
                                        "MRjEso": {
                                            "column_title": "Off-menu interventions (2029-30)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "ZzaODW",
                                "form_name": "payment-profile-and-spend-forecast",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us how you have developed your indicative spend forecast and why it is important for spend to occur in these years.",
                            },
                            {
                                "field_id": "Grlvkx",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for pre-approved interventions in year 2.",
                                    {
                                        "wYgMdi": {"column_title": "Cohesion (2027-28)", "type": "numberField"},
                                        "YlgCLY": {
                                            "column_title": "Education and opportunity (2027-28)",
                                            "type": "numberField",
                                        },
                                        "ESRHVS": {
                                            "column_title": "Health and wellbeing (2027-28)",
                                            "type": "numberField",
                                        },
                                        "qUrvtI": {"column_title": "Housing (2027-28)", "type": "numberField"},
                                    },
                                ],
                            },
                            {
                                "field_id": "ZaxlkA",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for programme delivery funding (revenue) throughout the programme.",
                                    {
                                        "YQGJbm": {
                                            "column_title": "Programme delivery funding - revenue (2026-27)",
                                            "type": "numberField",
                                        },
                                        "VmCcNW": {
                                            "column_title": "Programme delivery funding - revenue (2027-28)",
                                            "type": "numberField",
                                        },
                                        "pCCkfZ": {
                                            "column_title": "Programme delivery funding - revenue (2028-29)",
                                            "type": "numberField",
                                        },
                                        "aaOhAH": {
                                            "column_title": "Programme delivery funding - revenue (2029-30)",
                                            "type": "numberField",
                                        },
                                        "ehgQSG": {
                                            "column_title": "Programme delivery funding - revenue (2030-31)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "ZaxlkA",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "",
                                    {
                                        "mmMPXd": {
                                            "column_title": "Programme delivery funding - revenue (2031-32)",
                                            "type": "numberField",
                                        },
                                        "iLMwbk": {
                                            "column_title": "Programme delivery funding - revenue (2032-33)",
                                            "type": "numberField",
                                        },
                                        "ThaiNt": {
                                            "column_title": "Programme delivery funding - revenue (2033-34)",
                                            "type": "numberField",
                                        },
                                        "ROCfYU": {
                                            "column_title": "Programme delivery funding - revenue (2034-35)",
                                            "type": "numberField",
                                        },
                                        "qMNUxP": {
                                            "column_title": "Programme delivery funding - revenue (2035-36)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "MEaRya",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for pre-approved interventions in year 1.",
                                    {
                                        "zsdDQk": {"column_title": "Cohesion (2026-27)", "type": "numberField"},
                                        "DBqPzO": {
                                            "column_title": "Education and opportunity (2027-28)",
                                            "type": "numberField",
                                        },
                                        "MNzARq": {
                                            "column_title": "Health and wellbeing (2028-29)",
                                            "type": "numberField",
                                        },
                                        "IVFTCQ": {"column_title": "Housing (2029-30)", "type": "numberField"},
                                    },
                                ],
                            },
                            {
                                "field_id": "MEaRya",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "",
                                    {
                                        "nqmOwu": {
                                            "column_title": "Regeneration, high streets and heritage (2030-31)",
                                            "type": "numberField",
                                        },
                                        "UbTbvU": {
                                            "column_title": "Safety and security (2031-32)",
                                            "type": "numberField",
                                        },
                                        "qNiSsO": {"column_title": "Transport (2032-33)", "type": "numberField"},
                                        "hNACOp": {
                                            "column_title": "Work, productivity and skills (2033-34)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "Grlvkx",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "",
                                    {
                                        "VsEWYE": {
                                            "column_title": "Regeneration, high streets and heritage (2027-28)",
                                            "type": "numberField",
                                        },
                                        "YIpOAe": {
                                            "column_title": "Safety and security (2027-28)",
                                            "type": "numberField",
                                        },
                                        "lSlyHK": {"column_title": "Transport (2027-28)", "type": "numberField"},
                                        "TaXzeh": {
                                            "column_title": "Work, productivity and skills (2027-28)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "gEOHHl",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for pre-approved interventions in year 3.",
                                    {
                                        "FwurgE": {"column_title": "Cohesion (2028-29)", "type": "numberField"},
                                        "tmOkiG": {
                                            "column_title": "Education and opportunity (2028-29)",
                                            "type": "numberField",
                                        },
                                        "sSQLwH": {
                                            "column_title": "Health and wellbeing (2028-29)",
                                            "type": "numberField",
                                        },
                                        "uUTyWH": {"column_title": "Housing (2028-29)", "type": "numberField"},
                                    },
                                ],
                            },
                            {
                                "field_id": "gEOHHl",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "",
                                    {
                                        "ZsNcbA": {
                                            "column_title": "Regeneration, high streets and heritage (2028-29)",
                                            "type": "numberField",
                                        },
                                        "iuTXHe": {
                                            "column_title": "Safety and security (2028-29)",
                                            "type": "numberField",
                                        },
                                        "lXTtKN": {"column_title": "Transport (2028-29)", "type": "numberField"},
                                        "FfSahl": {
                                            "column_title": "Work, productivity and skills (2028-29)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "yYqyaG",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for pre-approved interventions in year 4.",
                                    {
                                        "ygHERI": {"column_title": "Cohesion (2029-30)", "type": "numberField"},
                                        "QoEuWY": {
                                            "column_title": "Education and opportunity (2029-30)",
                                            "type": "numberField",
                                        },
                                        "QpOTwg": {
                                            "column_title": "Health and wellbeing (2029-30)",
                                            "type": "numberField",
                                        },
                                        "jCEizE": {"column_title": "Housing (2029-30)", "type": "numberField"},
                                    },
                                ],
                            },
                            {
                                "field_id": "yYqyaG",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "",
                                    {
                                        "zODcnS": {
                                            "column_title": "Regeneration, high streets and heritage (2029-30)",
                                            "type": "numberField",
                                        },
                                        "pAnzYr": {
                                            "column_title": "Safety and security (2029-30)",
                                            "type": "numberField",
                                        },
                                        "ZKFXMr": {"column_title": "Transport (2029-30)", "type": "numberField"},
                                        "flkyla": {
                                            "column_title": "Work, productivity and skills (2029-30)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "QEywSA",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for any off-menu interventions in the first investment period.",
                                    {
                                        "NCgxYf": {
                                            "column_title": "Off-menu interventions (2026-27)",
                                            "type": "numberField",
                                        },
                                        "afjufs": {
                                            "column_title": "Off-menu interventions (2027-28)",
                                            "type": "numberField",
                                        },
                                        "EbZeKz": {
                                            "column_title": "Off-menu interventions (2028-29)",
                                            "type": "numberField",
                                        },
                                        "MRjEso": {
                                            "column_title": "Off-menu interventions (2029-30)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "aUQnBP",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us your indicative spend forecast for management costs in the first investment period.",
                                    {
                                        "QVuIFv": {"column_title": "Management costs (2026-27)", "type": "numberField"},
                                        "GHFRTw": {"column_title": "Management costs (2027-28)", "type": "numberField"},
                                        "sAelLv": {"column_title": "Management costs (2028-29)", "type": "numberField"},
                                        "ZvlDXd": {"column_title": "Management costs (2029-30)", "type": "numberField"},
                                    },
                                ],
                            },
                            {
                                "field_id": "aLeDKy",
                                "form_name": "pfn-rp-payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "table",
                                "question": [
                                    "Tell us about any unknown uses of funding in the first investment period.",
                                    {
                                        "wajlvP": {
                                            "column_title": "Unknown uses of funding (2026-27)",
                                            "type": "numberField",
                                        },
                                        "bPbTEe": {
                                            "column_title": "Unknown uses of funding (2027-28)",
                                            "type": "numberField",
                                        },
                                        "XGBxKK": {
                                            "column_title": "Unknown uses of funding (2028-29)",
                                            "type": "numberField",
                                        },
                                        "fqmDlx": {
                                            "column_title": "Unknown uses of funding (2029-30)",
                                            "type": "numberField",
                                        },
                                    },
                                ],
                            },
                            {
                                "field_id": "igStco",
                                "form_name": "payment-profile-and-spend-forecast",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Tell us your indicative spend forecast for programme delivery funding (capital) throughout the programme.",
                            },
                            {
                                "field_id": "vQurBX",
                                "form_name": "capacity-funding",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us how you will use any remaining capacity funding since your last submission and outline how you plan to use your remaining capacity funding allocations.",
                            },
                            {
                                "field_id": "WLsVkX",
                                "form_name": "management-costs",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us why you have not received approval from your Neighbourhood Board on the funding.",
                            },
                            {
                                "field_id": "dpeZBx",
                                "form_name": "management-costs",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Have you received approval from your Neighbourhood Board to use revenue funding for management costs, and approval on how much funding will be used?",
                            },
                            {
                                "field_id": "WgghkV",
                                "form_name": "management-costs",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you plan to use any programme delivery funding to cover management costs in the first investment period?  ",
                            },
                            {
                                "field_id": "BTswKL",
                                "form_name": "management-costs",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us what the programme delivery funding will be used for.",
                            },
                            {
                                "field_id": "ZRERCV",
                                "form_name": "milestones",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Which milestones are relevant for your place?",
                            },
                            {
                                "field_id": "fXhfQu",
                                "form_name": "milestones",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Would you like to add any bespoke milestones?",
                            },
                            {
                                "field_id": "POAlfg",
                                "form_name": "milestones",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Summarise the activities for this milestone, and provide the estimated start and completion dates.",
                            },
                            {
                                "field_id": "mFpuWM",
                                "form_name": "milestones",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Summarise the activities for this milestone, and provide the estimated start and completion dates.",
                            },
                            {
                                "field_id": "rrPXVD",
                                "form_name": "milestones",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Summarise the activities for this milestone, and provide the estimated start and completion dates.",
                            },
                            {
                                "field_id": "wnHKSa",
                                "form_name": "milestones",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Summarise the activities for this milestone, and provide the estimated start and completion dates.",
                            },
                            {
                                "field_id": "PHFgHg",
                                "form_name": "milestones",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Summarise the activities for this milestone, and provide the estimated start and completion dates.",
                            },
                            {
                                "field_id": "cfiJyU",
                                "form_name": "milestones",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Tell us about the milestone.",
                            },
                        ],
                    }
                ],
            },
            {
                "id": "have-the-local-community-and-key-stakeholders-been-key-in-informing-and-shaping-the-plan-and-will-they-be-actively-involved-in-evolution-and-delivery-of-the-plan-throughout-the-next-decade",
                "name": "Have the local community and key stakeholders been key in informing and shaping the plan and will they be actively involved in evolution and delivery of the plan throughout the next decade?",
                "themes": [
                    {
                        "id": "have-the-local-community-and-key-stakeholders-been-key-in-informing-and-shaping-the-plan-and-will-they-be-actively-involved-in-evolution-and-delivery-of-the-plan-throughout-the-next-decade",
                        "name": "Have the local community and key stakeholders been key in informing and shaping the plan and will they be actively involved in evolution and delivery of the plan throughout the next decade?",
                        "answers": [
                            {
                                "field_id": "nfJFsF",
                                "form_name": "community-engagement-and-support",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Full name",
                            },
                            {
                                "field_id": "CCRPQy",
                                "form_name": "community-engagement-and-support",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Constituency",
                            },
                            {
                                "field_id": "TCoatJ",
                                "form_name": "community-engagement-and-support",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us why you have not consulted your MP during development of this plan and why they have not reviewed it prior to submission.",
                            },
                            {
                                "field_id": "gAJCVy",
                                "form_name": "community-engagement-and-support",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us how you have engaged with your local community and key stakeholders to develop your Regeneration Plan.",
                            },
                            {
                                "field_id": "WBXREe",
                                "form_name": "community-engagement-and-support",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us why you have not consulted the MP for the constituency making up between 10% to 25% of agreed geography.",
                            },
                            {
                                "field_id": "iMOpXS",
                                "form_name": "community-engagement-and-support",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us why you haven't consulted with the relevant Mayoral Combined Authority.",
                            },
                            {
                                "field_id": "OKvzvc",
                                "form_name": "community-engagement-and-support",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us why the MP for the constituency making up more than 25% of agreed place geography has not reviewed the plan.",
                            },
                            {
                                "field_id": "EdCIXR",
                                "form_name": "community-engagement-and-support",
                                "field_type": "multiInputField",
                                "presentation_type": "text",
                                "question": "Tell us the name and constituency for the MPs who have reviewed the plan.",
                            },
                            {
                                "field_id": "kFlcRf",
                                "form_name": "community-engagement-and-support",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is your place in a Mayoral Combined Authority?",
                            },
                            {
                                "field_id": "cRASmW",
                                "form_name": "community-engagement-and-support",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the MP for your place been consulted during development of this plan and reviewed it prior to submission?",
                            },
                            {
                                "field_id": "IvRZON",
                                "form_name": "community-engagement-and-support",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Have you consulted with the relevant Mayoral Combined Authority on the content of your Regeneration Plan?",
                            },
                            {
                                "field_id": "VqIKfJ",
                                "form_name": "community-engagement-and-support",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does the constituency of another MP make up 25% or more of your agreed place geography?",
                            },
                            {
                                "field_id": "VhbSCH",
                                "form_name": "community-engagement-and-support",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does the constituency of another MP make up between 10% to 25% of your agreed place geography?",
                            },
                            {
                                "field_id": "zsVooC",
                                "form_name": "community-engagement-and-support",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the MP for the constituency making up more than 25% been consulted, and reviewed the plan prior to submission?",
                            },
                            {
                                "field_id": "ZOTBdq",
                                "form_name": "community-engagement-and-support",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the MP been consulted on any parts of your plan that impact on areas within their constituency?",
                            },
                            {
                                "field_id": "yMWAhw",
                                "form_name": "10-year-vision",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Would you like to upload any supporting documents?",
                            },
                            {
                                "field_id": "QdfSRQ",
                                "form_name": "10-year-vision",
                                "field_type": "clientSideFileUploadField",
                                "presentation_type": "text",
                                "question": "Upload your 10-year vision.",
                            },
                            {
                                "field_id": "lVzOPc",
                                "form_name": "10-year-vision",
                                "field_type": "clientSideFileUploadField",
                                "presentation_type": "text",
                                "question": "Upload any supporting documents and provide a brief description of their purpose.",
                            },
                            {
                                "field_id": "HzWBci",
                                "form_name": "10-year-vision",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Specify the purpose for each document using the format: 'File name - purpose'. ",
                            },
                            {
                                "field_id": "SZrPXB",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about the local challenges you have identified as priorities to address in the first investment period and why.",
                            },
                            {
                                "field_id": "DOWpEu",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about any local opportunities for improvement or investment that you have identified and wish to pursue in the first investment period.",
                            },
                            {
                                "field_id": "XaZCkd",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about the local challenges you have identified as priorities to address in the first investment period and why.",
                            },
                            {
                                "field_id": "aJyHdS",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about any local opportunities for improvement or investment that you have identified and wish to pursue in the first investment period.",
                            },
                            {
                                "field_id": "PjdnJZ",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about the local challenges you have identified as priorities to address in the first investment period and why.",
                            },
                            {
                                "field_id": "AORTLp",
                                "form_name": "4-year-investment-plan:-key-priorities",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about any local opportunities for improvement or investment that you have identified and wish to pursue in the first investment period.",
                            },
                        ],
                    }
                ],
            },
            {
                "id": "will-appropriate-governance-arrangements-be-in-place-to-fully-realise-the-intended-role-of-the-neighbourhood-board-and-to-allow-the-board-to-work-in-partnership-with-the-accountable-body-to-deliver-the-programme-successfully",
                "name": "Will appropriate governance arrangements be in place to fully realise the intended role of the Neighbourhood Board and to allow the board to work in partnership with the accountable body to deliver the programme successfully?",
                "themes": [
                    {
                        "id": "will-appropriate-governance-arrangements-be-in-place-to-fully-realise-the-intended-role-of-the-neighbourhood-board-and-to-allow-the-board-to-work-in-partnership-with-the-accountable-body-to-deliver-the-programme-successfully",
                        "name": "Will appropriate governance arrangements be in place to fully realise the intended role of the Neighbourhood Board and to allow the board to work in partnership with the accountable body to deliver the programme successfully?",
                        "answers": [
                            {
                                "field_id": "kWXPPv",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Have you considered environmental impacts when designing your investment plan? ",
                            },
                            {
                                "field_id": "EIcoEK",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to consider their environmental duty when implementing the investment plan?",
                            },
                            {
                                "field_id": "RYVPtY",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to ensure that any funds awarded through the programme are done in compliance with the appropriate public contract regulations?",
                            },
                            {
                                "field_id": "WipKsj",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you have a programme risk register with appropriate arrangements in place to manage risks identified?",
                            },
                            {
                                "field_id": "OrenNF",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you have a fraud risk assessment for this programme with appropriate arrangements in place to manage risks identified?",
                            },
                            {
                                "field_id": "AWQFzI",
                                "form_name": "management-of-funds",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Which country is your place based in?",
                            },
                            {
                                "field_id": "vVSvhr",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to consider their public sector equality duty when implementing the investment plan?",
                            },
                            {
                                "field_id": "NlrBUG",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to consider Section 75 of the Northern Ireland Act when implementing the investment plan?",
                            },
                            {
                                "field_id": "bqBGRA",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to ensure that the requirements of the Subsidy Control Act will be followed when administering the funding? ",
                            },
                            {
                                "field_id": "PdPQIB",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to ensure that the requirements of the Subsidy Control Act and state aid regulations will be followed when administering the funding? ",
                            },
                            {
                                "field_id": "hKHuoX",
                                "form_name": "management-of-funds",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us why you have not considered environmental impacts when designing your investment plan.",
                            },
                            {
                                "field_id": "qjonxe",
                                "form_name": "management-of-funds",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us how your Neighbourhood Board will identify and select specific projects for investment across the first investment period.",
                            },
                            {
                                "field_id": "fhcfgc",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "lQDKjX",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "vtaqXE",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "huYOGb",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "ctidtw",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "ahjTmQ",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "CiZzLy",
                                "form_name": "management-of-funds",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us how the accountable body will carry out fund oversight functions in the first investment period.",
                            },
                            {
                                "field_id": "UVGygK",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "cvQuzc",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "vbKOOv",
                                "form_name": "available-resources-and-skills",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us about the resources and skills available to support delivery in the first investment period.",
                            },
                        ],
                    }
                ],
            },
            {
                "id": "will-appropriate-control-processes-will-be-in-place-for-management-of-public-funds",
                "name": "Will appropriate control processes will be in place for management of public funds?",
                "themes": [
                    {
                        "id": "will-appropriate-control-processes-will-be-in-place-for-management-of-public-funds",
                        "name": "Will appropriate control processes will be in place for management of public funds?",
                        "answers": [
                            {
                                "field_id": "lsLcXO",
                                "form_name": "declarations",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Which country is your place based in?",
                            },
                            {
                                "field_id": "qpeEcB",
                                "form_name": "declarations",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Confirm you have read and agree with the declarations.",
                            },
                            {
                                "field_id": "xJzeTP",
                                "form_name": "declarations",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Confirm you have read and agree with the declarations.",
                            },
                            {
                                "field_id": "rSvAwx",
                                "form_name": "declarations",
                                "field_type": "checkboxesField",
                                "presentation_type": "text",
                                "question": "Confirm you have read and agree with the declarations.",
                            },
                            {
                                "field_id": "kWXPPv",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Have you considered environmental impacts when designing your investment plan? ",
                            },
                            {
                                "field_id": "EIcoEK",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to consider their environmental duty when implementing the investment plan?",
                            },
                            {
                                "field_id": "RYVPtY",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to ensure that any funds awarded through the programme are done in compliance with the appropriate public contract regulations?",
                            },
                            {
                                "field_id": "WipKsj",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you have a programme risk register with appropriate arrangements in place to manage risks identified?",
                            },
                            {
                                "field_id": "OrenNF",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you have a fraud risk assessment for this programme with appropriate arrangements in place to manage risks identified?",
                            },
                            {
                                "field_id": "AWQFzI",
                                "form_name": "management-of-funds",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Which country is your place based in?",
                            },
                            {
                                "field_id": "vVSvhr",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to consider their public sector equality duty when implementing the investment plan?",
                            },
                            {
                                "field_id": "NlrBUG",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to consider Section 75 of the Northern Ireland Act when implementing the investment plan?",
                            },
                            {
                                "field_id": "bqBGRA",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to ensure that the requirements of the Subsidy Control Act will be followed when administering the funding? ",
                            },
                            {
                                "field_id": "PdPQIB",
                                "form_name": "management-of-funds",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the accountable body made appropriate arrangements to ensure that the requirements of the Subsidy Control Act and state aid regulations will be followed when administering the funding? ",
                            },
                            {
                                "field_id": "hKHuoX",
                                "form_name": "management-of-funds",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us why you have not considered environmental impacts when designing your investment plan.",
                            },
                            {
                                "field_id": "qjonxe",
                                "form_name": "management-of-funds",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us how your Neighbourhood Board will identify and select specific projects for investment across the first investment period.",
                            },
                            {
                                "field_id": "fhcfgc",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "lQDKjX",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "vtaqXE",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "huYOGb",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "ctidtw",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "ahjTmQ",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "CiZzLy",
                                "form_name": "management-of-funds",
                                "field_type": "multilineTextField",
                                "presentation_type": "text",
                                "question": "Tell us how the accountable body will carry out fund oversight functions in the first investment period.",
                            },
                            {
                                "field_id": "UVGygK",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                            {
                                "field_id": "cvQuzc",
                                "form_name": "management-of-funds",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Tell us when arrangements will be put in place.",
                            },
                        ],
                    }
                ],
            },
        ],
    }
]
