"""Add change request count

Revision ID: 010_add_change_request_count
Revises: 009_relax_flag_json_constraints
Create Date: 2025-01-21 15:05:15.304121

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "010_add_change_request_count"
down_revision = "009_relax_flag_json_constraints"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("no_of_change_request_state_forms", sa.Integer(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_column("no_of_change_request_state_forms")

    # ### end Alembic commands ###
