"""Application submitted and status

Revision ID: 012_application_submitted_and_st
Revises: 011_reporting_rounds
Create Date: 2025-01-25 17:39:22.955589

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "012_application_submitted_and_st"
down_revision = "011_reporting_rounds"
branch_labels = None
depends_on = None

testlivestatus_enum = postgresql.ENUM("TEST", "LIVE", name="testlivestatus", create_type=False)


def upgrade():
    testlivestatus_enum.create(op.get_bind().engine, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proto_application", schema=None) as batch_op:
        batch_op.add_column(sa.Column("submitted", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("test_live_status", testlivestatus_enum, nullable=True))

    with op.batch_alter_table("proto_application", schema=None) as batch_op:
        batch_op.alter_column("test_live_status", existing_type=testlivestatus_enum, nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proto_application", schema=None) as batch_op:
        batch_op.drop_column("test_live_status")
        batch_op.drop_column("submitted")

    # ### end Alembic commands ###
