"""Scores and comments

Revision ID: 013_scores_and_comments
Revises: 012_application_submitted_and_st
Create Date: 2025-01-25 23:31:21.796738

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "013_scores_and_comments"
down_revision = "012_application_submitted_and_st"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proto_comment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], name=op.f("fk_proto_comment_account_id_account")),
        sa.ForeignKeyConstraint(
            ["application_id"], ["proto_application.id"], name=op.f("fk_proto_comment_application_id_proto_application")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["proto_data_collection_instance_section_data.id"],
            name=op.f("fk_proto_comment_section_id_proto_data_collection_instance_section_data"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proto_comment")),
    )
    op.create_table(
        "proto_score",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], name=op.f("fk_proto_score_account_id_account")),
        sa.ForeignKeyConstraint(
            ["application_id"], ["proto_application.id"], name=op.f("fk_proto_score_application_id_proto_application")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["proto_data_collection_instance_section_data.id"],
            name=op.f("fk_proto_score_section_id_proto_data_collection_instance_section_data"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proto_score")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proto_score")
    op.drop_table("proto_comment")
    # ### end Alembic commands ###
