"""section template id

Revision ID: 016_section_template_id
Revises: 015_add_conditions
Create Date: 2025-02-20 11:45:23.626852

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "016_section_template_id"
down_revision = "015_add_conditions"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proto_data_collection_definition_section", schema=None) as batch_op:
        batch_op.add_column(sa.Column("template_section_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_proto_data_collection_definition_section_template_section_id_template_section"),
            "template_section",
            ["template_section_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proto_data_collection_definition_section", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_proto_data_collection_definition_section_template_section_id_template_section"),
            type_="foreignkey",
        )
        batch_op.drop_column("template_section_id")

    # ### end Alembic commands ###
