"""question validations

Revision ID: 018_question_validations
Revises: 017_add_expression_to_conditions
Create Date: 2025-02-21 13:08:46.808724

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "018_question_validations"
down_revision = "017_add_expression_to_conditions"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proto_data_collection_question_validation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_question_id", sa.Integer(), nullable=True),
        sa.Column("expression", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_question_id"],
            ["proto_data_collection_definition_question.id"],
            name=op.f(
                "fk_proto_data_collection_question_validation_depends_on_question_id_proto_data_collection_definition_question"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["proto_data_collection_definition_question.id"],
            name=op.f(
                "fk_proto_data_collection_question_validation_question_id_proto_data_collection_definition_question"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proto_data_collection_question_validation")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proto_data_collection_question_validation")
    # ### end Alembic commands ###
