"""validations from template

Revision ID: 019_validations_from_template
Revises: 018_question_validations
Create Date: 2025-02-21 14:07:03.074928

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "019_validations_from_template"
down_revision = "018_question_validations"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template_validation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_question_id", sa.Integer(), nullable=True),
        sa.Column("expression", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_question_id"],
            ["template_question.id"],
            name=op.f("fk_template_validation_depends_on_question_id_template_question"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["template_question.id"], name=op.f("fk_template_validation_question_id_template_question")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_validation")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template_validation")
    # ### end Alembic commands ###
