"""validation opt

Revision ID: 027_validation_opt
Revises: 026_optional_app_submitter
Create Date: 2025-03-03 06:39:26.942255

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "027_validation_opt"
down_revision = "026_optional_app_submitter"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proto_data_collection_question_validation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False))

    with op.batch_alter_table("template_validation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template_validation", schema=None) as batch_op:
        batch_op.drop_column("options")

    with op.batch_alter_table("proto_data_collection_question_validation", schema=None) as batch_op:
        batch_op.drop_column("options")

    # ### end Alembic commands ###
