"""reference data edit

Revision ID: 029_reference_data_edit
Revises: 028_reference_data
Create Date: 2025-03-04 15:03:36.136145

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "029_reference_data_edit"
down_revision = "028_reference_data"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_store_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.Integer(), nullable=False))

    with op.batch_alter_table("template_question", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reference_data_source_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_template_question_reference_data_source_id_data_store"),
            "data_store",
            ["reference_data_source_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template_question", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_template_question_reference_data_source_id_data_store"), type_="foreignkey"
        )
        batch_op.drop_column("reference_data_source_id")

    with op.batch_alter_table("data_store_entry", schema=None) as batch_op:
        batch_op.drop_column("version")

    # ### end Alembic commands ###
