"""reference fix

Revision ID: 030_reference_fix
Revises: 029_reference_data_edit
Create Date: 2025-03-04 15:39:34.464576

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "030_reference_fix"
down_revision = "029_reference_data_edit"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_store", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_name", sa.String(), nullable=False))
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_store", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column("collection_name")

    # ### end Alembic commands ###
