# ruff: noqa: E501

unscored_sections = [
    {
        "id": "unscored",
        "name": "Unscored",
        "sub_criteria": [
            {
                "id": "organisation_details",
                "name": "Organisation details",
                "themes": [
                    {
                        "id": "organisation_details",
                        "name": "Organisation details",
                        "answers": [
                            {
                                "field_id": "Gaibvs",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Enter your registration reference number.",
                            },
                            {
                                "field_id": "JgqOiG",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Full name",
                            },
                            {
                                "field_id": "fSohIv",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Organisation",
                            },
                            {
                                "field_id": "JeGsjj",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Role",
                            },
                            {
                                "field_id": "bzFqFj",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "emailAddressField",
                                "presentation_type": "text",
                                "question": "Email address",
                            },
                            {
                                "field_id": "oWuVdi",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "telephoneNumberField",
                                "presentation_type": "text",
                                "question": "Contact number",
                            },
                            {
                                "field_id": "trYDMJ",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "What is the name of your organisation?",
                            },
                            {
                                "field_id": "rocaEG",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does your organisation have an alternative name?",
                            },
                            {
                                "field_id": "LAIyWE",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "What is the alternative name of your organisation?",
                            },
                            {
                                "field_id": "PsvKdR",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "ukAddressField",
                                "presentation_type": "text",
                                "question": "What is your organisation's address?",
                            },
                            {
                                "field_id": "wMrxig",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has your organisation been established for 2 years or more?",
                            },
                            {
                                "field_id": "OgQBfd",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "What is the legal status of your organisation?",
                            },
                            {
                                "field_id": "COnttV",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is the organisation a charity?",
                            },
                            {
                                "field_id": "Lwzeak",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Where is the charity registered?",
                            },
                            {
                                "field_id": "fMjwht",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "What is your registered charity number?",
                            },
                            {
                                "field_id": "EQjFsc",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you have a company registration number?",
                            },
                            {
                                "field_id": "QCszWL",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "What is your company registration number?",
                            },
                            {
                                "field_id": "iRkMMO",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is your organisation controlled by another entity?",
                            },
                            {
                                "field_id": "bKDWQe",
                                "form_name": "cham-apply-registration-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "What is the name of the entity that controls your organisation?",
                            },
                        ],
                    },
                ],
            },
        ],
    },
]
