"""Removing unused contact fields from round

Revision ID: 011_removing_unused_contact_fiel
Revises: 010_
Create Date: 2025-02-04 10:38:05.010376

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "011_removing_unused_contact_fiel"
down_revision = "010_"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("contact_textphone")
        batch_op.drop_column("contact_us_banner_json")
        batch_op.drop_column("contact_phone")
        batch_op.drop_column("support_days")
        batch_op.drop_column("reference_contact_page_over_email")
        batch_op.drop_column("support_times")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("support_times", sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column("reference_contact_page_over_email", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(sa.Column("support_days", sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("contact_phone", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(
            sa.Column(
                "contact_us_banner_json", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(sa.Column("contact_textphone", sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
