"""Add display_name to form_definition

Revision ID: 016_add_display_name_to_form_de
Revises: 015_add_form_definition_table
Create Date: 2025-09-18 08:41:02.682162

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "016_add_display_name_to_form_de"
down_revision = "015_add_form_definition_table"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("form_definition", schema=None) as batch_op:
        batch_op.add_column(sa.Column("display_name", sa.Text(), nullable=True))
        batch_op.drop_constraint("uq_form_definition_name", type_="unique")
        batch_op.alter_column("name", new_column_name="url_path")
        batch_op.create_unique_constraint(batch_op.f("uq_form_definition_url_path"), ["url_path"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("form_definition", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_form_definition_url_path"), type_="unique")
        batch_op.alter_column("url_path", new_column_name="name")
        batch_op.create_unique_constraint("uq_form_definition_name", ["name"], postgresql_nulls_not_distinct=False)
        batch_op.drop_column("display_name")

    # ### end Alembic commands ###
