"""Adds 'send_incomplete_application_emails' property to Round model

Revision ID: 017_adds_send_incomplete_applica
Revises: 016_add_display_name_to_form_de
Create Date: 2025-11-27 13:14:06.367884

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "017_adds_send_incomplete_applica"
down_revision = "016_add_display_name_to_form_de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("send_incomplete_application_emails", sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("send_incomplete_application_emails")

    # ### end Alembic commands ###
