"""adding send_deadline_reminder_emails to Round model

Revision ID: 019_adding_send_deadline_reminde
Revises: 018_adds_send_incomplete_applica
Create Date: 2026-01-13 11:55:58.978579

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "019_adding_send_deadline_reminde"
down_revision = "018_adds_send_incomplete_applica"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("send_deadline_reminder_emails", sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("send_deadline_reminder_emails")

    # ### end Alembic commands ###
