"""adding pii_deletion_completed to Round model

Revision ID: 020_adding_pii_deletion_complete
Revises: 019_adding_send_deadline_reminde
Create Date: 2026-03-03 08:50:31.139412

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "020_adding_pii_deletion_complete"
down_revision = "019_adding_send_deadline_reminde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("pii_deletion_completed", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("pii_deletion_completed")

    # ### end Alembic commands ###
