"""create PiiDeletionLog model

Revision ID: 021_create_piideletionlog_model
Revises: 020_adding_pii_deletion_complete
Create Date: 2026-03-18 09:57:40.438232

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "021_create_piideletionlog_model"
down_revision = "020_adding_pii_deletion_complete"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pii_deletion_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("round_id", sa.Uuid(), nullable=False),
        sa.Column("deletion_timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_by_email", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["round_id"], ["round.id"], name=op.f("fk_pii_deletion_log_round_id_round")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pii_deletion_log")),
    )
    with op.batch_alter_table("pii_deletion_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pii_deletion_log_round_id"), ["round_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pii_deletion_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pii_deletion_log_round_id"))

    op.drop_table("pii_deletion_log")
    # ### end Alembic commands ###
