"""change pii_deletion_completed field to pii_deleted_for_applications on Round model
Revision ID: 022_change_pii_deletion_complete
Revises: 021_create_piideletionlog_model
Create Date: 2026-03-23 12:52:14.056992
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "022_change_pii_deletion_complete"
down_revision = "021_create_piideletionlog_model"
branch_labels = None
depends_on = None

pii_deletion_scope_enum = postgresql.ENUM(
    "UN_SUBMITTED",
    "SUBMITTED",
    "ALL",
    name="piideletedforapplications",
    create_type=False,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    # Ensure the enum type exists; create it if missing
    pii_deletion_scope_enum.create(bind, checkfirst=True)

    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pii_deleted_for_applications",
                pii_deletion_scope_enum,
                nullable=True,
                server_default=None,
            )
        )
        batch_op.drop_column("pii_deletion_completed")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pii_deletion_completed", sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.false()
            )
        )
        batch_op.drop_column("pii_deleted_for_applications")

    # ### end Alembic commands ###
