LOADER_CONFIG = {
    "sections_config": [
        {"section_name": {"en": "1. Before you start", "cy": ""}, "tree_path": "1059.1.1", "requires_feedback": None},
        {
            "section_name": {"en": "1.1 Name your application", "cy": ""},
            "tree_path": "1059.1.1.1",
            "form_name_json": {"en": "cfa-r1-name-your-application", "cy": ""},
        },
        {
            "section_name": {"en": "2. About your organisation", "cy": ""},
            "tree_path": "1059.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 About your organisation", "cy": ""},
            "tree_path": "1059.1.2.1",
            "form_name_json": {"en": "cfa-r1-about-your-organisation", "cy": ""},
        },
        {
            "section_name": {"en": "3. Your skills and experience", "cy": ""},
            "tree_path": "1059.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Skills and experience", "cy": ""},
            "tree_path": "1059.1.3.1",
            "form_name_json": {"en": "cfa-r1-skills-and-experience", "cy": ""},
        },
        {"section_name": {"en": "4. Your project", "cy": ""}, "tree_path": "1059.1.4", "requires_feedback": None},
        {
            "section_name": {"en": "4.1 Your project ", "cy": ""},
            "tree_path": "1059.1.4.1",
            "form_name_json": {"en": "cfa-r1-your-project", "cy": ""},
        },
        {
            "section_name": {"en": "5. Risk and deliverability", "cy": ""},
            "tree_path": "1059.1.5",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "5.1 Risk and deliverability", "cy": ""},
            "tree_path": "1059.1.5.1",
            "form_name_json": {"en": "cfa-r1-risk-and-deliverability", "cy": ""},
        },
        {"section_name": {"en": "6. Value for money", "cy": ""}, "tree_path": "1059.1.6", "requires_feedback": None},
        {
            "section_name": {"en": "6.1 Value for money", "cy": ""},
            "tree_path": "1059.1.6.1",
            "form_name_json": {"en": "cfa-r1-value-for-money", "cy": ""},
        },
        {"section_name": {"en": "7. Social value", "cy": ""}, "tree_path": "1059.1.7", "requires_feedback": None},
        {
            "section_name": {"en": "7.1 Social value", "cy": ""},
            "tree_path": "1059.1.7.1",
            "form_name_json": {"en": "cfa-r1-social-value", "cy": ""},
        },
        {"section_name": {"en": "8. Declarations", "cy": ""}, "tree_path": "1059.1.8", "requires_feedback": None},
        {
            "section_name": {"en": "8.1 Declarations", "cy": ""},
            "tree_path": "1059.1.8.1",
            "form_name_json": {"en": "cfa-r1-declarations", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "35418582-d784-4715-8445-3b1f34320e3c",
        "short_name": "CFA",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2025-01-16273",
        "funding_type": "COMPETITIVE",
        "owner_organisation_name": "",
        "owner_organisation_shortname": "",
        "owner_organisation_logo_uri": "",
        "name_json": {"en": "Communities for Afghans", "cy": ""},
        "title_json": {
            "en": "grant funding to be a Principal Sponsor for the Communities for Afghans scheme",
            "cy": "",
        },
        "description_json": {
            "en": "Communities for Afghans (CfA) phase 2 aims to accommodate 500 Afghan households (approximately 2750 individuals) on the Afghan Resettlement Programmes by the end of March 2031. The aim is to provide households with the tools that they need to integrate into society and promote cohesion between households and their local communities so that they can participate fully in UK life.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "25cca4ba-9dbe-45c7-ae2d-d14cadcd8bc6",
        "fund_id": "35418582-d784-4715-8445-3b1f34320e3c",
        "short_name": "R1",
        "opens": "2025-03-17T09:00:00",
        "assessment_start": "2025-04-11T09:00:00",
        "deadline": "2025-04-10T23:59:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-04-07T09:00:00",
        "assessment_deadline": "2025-05-07T17:00:00",
        "prospectus": "https://www.gov.uk/government/publications/communities-for-afghans-project-dluhc-policy-update/communities-for-afghans-phase-2-prospectus",
        "privacy_notice": "https://www.gov.uk/government/publications/communities-for-afghans-project-dluhc-policy-update/communities-for-afghans-phase-2-application-guidance",
        "contact_email": "sponsorship@communities.gov.uk",
        "instructions_json": {"en": None, "cy": None},
        "feedback_link": "",
        "project_name_field_id": "FuWchF",
        "application_guidance_json": {
            "en": "<h2 class='govuk-heading govuk-heading-s'>What we'll ask you for</h2> <p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p>",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": True},
        "title_json": {"en": "Round 1", "cy": None},
    },
    "base_path": 1059,
}
