LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Organisation details", "cy": ""},
            "tree_path": "1062.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Organisation details", "cy": ""},
            "tree_path": "1062.1.1.1",
            "form_name_json": {"en": "cham-apply-registration-details", "cy": ""},
        },
        {
            "section_name": {"en": "2. Business plan", "cy": ""},
            "tree_path": "1062.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Upload your business plan", "cy": ""},
            "tree_path": "1062.1.2.1",
            "form_name_json": {"en": "cham-apply-upload-your-business-plan", "cy": ""},
        },
        {
            "section_name": {"en": "3. Skills and experience", "cy": ""},
            "tree_path": "1062.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Skills and experience", "cy": ""},
            "tree_path": "1062.1.3.1",
            "form_name_json": {"en": "cham-apply-organisation-information", "cy": ""},
        },
        {
            "section_name": {"en": "4. Programme delivery", "cy": ""},
            "tree_path": "1062.1.4",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "4.1 Programme delivery", "cy": ""},
            "tree_path": "1062.1.4.1",
            "form_name_json": {"en": "cham-apply-programme-delivery", "cy": ""},
        },
        {
            "section_name": {"en": "5. Costs", "cy": ""},
            "tree_path": "1062.1.5",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "5.1 Costs and value for money", "cy": ""},
            "tree_path": "1062.1.5.1",
            "form_name_json": {"en": "cham-apply-costs-and-value-for-money", "cy": ""},
        },
        {
            "section_name": {"en": "6. Risks and reporting to MHCLG", "cy": ""},
            "tree_path": "1062.1.6",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "6.1 Risks and reporting to MHCLG", "cy": ""},
            "tree_path": "1062.1.6.1",
            "form_name_json": {
                "en": "cham-apply-risks-and-reporting-to-mhclg",
                "cy": "",
            },
        },
    ],
    "fund_config": {
        "id": "ce1fae51-fbc9-4c0b-8d9f-79948633fab6",
        "short_name": "CHAM",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2025-03-16396",
        "funding_type": "COMPETITIVE",
        "owner_organisation_name": "",
        "owner_organisation_shortname": "",
        "owner_organisation_logo_uri": "",
        "name_json": {"en": "Combatting Hate Against Muslims fund", "cy": ""},
        "title_json": {
            "en": "funding to monitor and report anti-Muslim hate to better support victims ",
            "cy": "",
        },
        "description_json": {
            "en": "This grant will support the work of an organisation or a consortium of organisations who wish to map a more accurate record of the hate incidents affecting Muslims across England. The reporting system should allow for the recording of both hate crimes, and non-crime hate incidents that occur online or in the real world.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "0ea715b0-8736-4621-9914-51410f9ccafb",
        "fund_id": "ce1fae51-fbc9-4c0b-8d9f-79948633fab6",
        "short_name": "APPLY",
        "opens": "2025-05-23T16:55:00",
        "assessment_start": "2025-05-18T23:00:00",
        "deadline": "2025-05-23T19:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-05-13T08:00:00",
        "assessment_deadline": "2025-06-01T23:59:00",
        "prospectus": "https://www.gov.uk/government/publications/combatting-hate-against-muslims-fund-prospectus",
        "privacy_notice": "https://www.gov.uk/government/publications/combatting-hate-against-muslims-fund-prospectus/combatting-hate-against-muslims-privacy-notice",
        "contact_email": "chambid@communities.gov.uk",
        "instructions_json": {
            "en": "You must have completed the registration form and received a registration reference number before applying to the Combatting Hate Against Muslims fund.",
            "cy": None,
        },
        "feedback_link": "",
        "project_name_field_id": "trYDMJ",
        "application_guidance_json": {
            "en": "Your application will be assessed against the criteria detailed in the grant's <a href='https://www.gov.uk/government/publications/combatting-hate-against-muslims-fund-prospectus'>prospectus</a>.<br><br>\r\nWe will assign a score for each criterion, based on information provided in both your business plan and your answers provided in the other sections of this application form.<br><br>\r\nYour answers should provide a concise summary of key information, but further detail can be provided in your business plan. <h2 class='govuk-heading govuk-heading-s'>What we'll ask you for</h2> <p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Application", "cy": None},
    },
    "base_path": 1062,
}
