LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Lead contact information", "cy": ""},
            "tree_path": "1061.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Lead contact information", "cy": ""},
            "tree_path": "1061.1.1.1",
            "form_name_json": {"en": "cham-reg-lead-contact-information", "cy": ""},
        },
        {
            "section_name": {"en": "2. Organisation information", "cy": ""},
            "tree_path": "1061.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Organisation information", "cy": ""},
            "tree_path": "1061.1.2.1",
            "form_name_json": {"en": "cham-reg-organisation-information", "cy": ""},
        },
        {
            "section_name": {"en": "3. Partner organisations", "cy": ""},
            "tree_path": "1061.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Partner organisations", "cy": ""},
            "tree_path": "1061.1.3.1",
            "form_name_json": {"en": "cham-reg-partner-organisations", "cy": ""},
        },
        {
            "section_name": {"en": "4. Declarations", "cy": ""},
            "tree_path": "1061.1.4",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "4.1 Declarations", "cy": ""},
            "tree_path": "1061.1.4.1",
            "form_name_json": {"en": "cham-reg-declarations", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "ce1fae51-fbc9-4c0b-8d9f-79948633fab6",
        "short_name": "CHAM",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2025-03-16396\t",
        "funding_type": "COMPETITIVE",
        "owner_organisation_name": "",
        "owner_organisation_shortname": "",
        "owner_organisation_logo_uri": "",
        "name_json": {"en": "Confronting Hate Against Muslims fund", "cy": ""},
        "title_json": {
            "en": "funding to monitor and report anti-Muslim hate to better support victims ",
            "cy": "",
        },
        "description_json": {
            "en": "This grant will support the work of an organisation or a consortium of organisations who wish to map a more accurate record of the hate incidents affecting Muslims across England. The reporting system should allow for the recording of both hate crimes, and non-crime hate incidents that occur online or in the real world.\t",
            "cy": "",
        },
    },
    "round_config": {
        "id": "b92044ee-17f0-4ed5-b4bb-d2ac04eaab54",
        "fund_id": "ce1fae51-fbc9-4c0b-8d9f-79948633fab6",
        "short_name": "REG",
        "opens": "2025-04-02T10:00:00",
        "assessment_start": "2025-04-02T10:00:00",
        "deadline": "2025-05-18T23:59:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-05-13T09:00:00",
        "assessment_deadline": "2025-06-01T23:59:00",
        "prospectus": "https://www.gov.uk/government/publications/confronting-hate-against-muslims-fund-prospectus",
        "privacy_notice": "https://www.gov.uk/government/publications/confronting-hate-against-muslims-fund-prospectus/confronting-hate-against-muslims-privacy-notice",
        "contact_email": "chambid@communities.gov.uk",
        "instructions_json": {
            "en": "You must complete this registration form to apply for the Confronting Hate Against Muslims Fund.",
            "cy": None,
        },
        "feedback_link": "",
        "project_name_field_id": "trYDMJ",
        "application_guidance_json": {
            "en": "<h2 class='govuk-heading govuk-heading-s'>What this process involves</h2> \r\n<p class='govuk-body'>We will ask for some basic information about your lead contact, your organisation, and any partner organisations if you are submitting as part of a joint bid.<br><br>You will receive an email to confirm that your registration has been submitted, along with a registration reference number. <br><br>You will be invited to complete the application form once that becomes available, quoting your registration reference number.</p>\t\r\n\r\n<h2 class='govuk-heading govuk-heading-s'>What we'll ask you for</h2> <p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p>\r\n\r\n<h2 class='govuk-heading govuk-heading-s'>How we'll use your information</h2> \r\n<p class='govuk-body'>Some of the answers you submit will be assessed automatically to show whether you are suitable to apply for the grant.<br><br>We also store this data so we can refer to it if you complete an application.<br><br>By completing this form, you also consent to share your data with our development support provider, who may direct you to information and support that they provide to all eligible applicants. They may also use your answers to determine whether you may be eligible for in-depth support with your application.<br><br>Read our <a href='https://www.gov.uk/government/publications/confronting-hate-against-muslims-fund-prospectus/confronting-hate-against-muslims-privacy-notice'>privacy notice</a> for more information.</p>",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Registration", "cy": None},
    },
    "base_path": 1061,
}
