LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Comprehensive Testing", "cy": ""},
            "tree_path": "1140.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Organisation Information", "cy": ""},
            "tree_path": "1140.1.1.1",
            "form_name_json": {"en": "ctdf-r2-organisation-information", "cy": ""},
        },
        {
            "section_name": {"en": "1.2 Project Details", "cy": ""},
            "tree_path": "1140.1.1.2",
            "form_name_json": {"en": "ctdf-r2-project-details", "cy": ""},
        },
        {
            "section_name": {"en": "1.3 Supporting Evidence", "cy": ""},
            "tree_path": "1140.1.1.3",
            "form_name_json": {"en": "ctdf-r2-supporting-evidence", "cy": ""},
        },
        {
            "section_name": {"en": "1.4 Declarations", "cy": ""},
            "tree_path": "1140.1.1.4",
            "form_name_json": {"en": "ctdf-r2-declarations", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "3dcfa617-cff8-4c2c-9edd-9568aa367d13",
        "short_name": "CTDF",
        "welsh_available": False,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "ggis_scheme_reference_number": "123-abc-456-def",
        "funding_type": "COMPETITIVE",
        "name_json": {"en": "Crash Test Dummy Fund", "cy": ""},
        "title_json": {"en": "funding for crash test dummies", "cy": ""},
        "description_json": {"en": "crash test dummies", "cy": ""},
    },
    "round_config": {
        "id": "8ecd7d64-1854-44ab-a10c-a7af4b8d68e2",
        "fund_id": "3dcfa617-cff8-4c2c-9edd-9568aa367d13",
        "short_name": "CR2",
        "opens": "2024-01-01T00:00:00",
        "assessment_start": "2024-01-01T00:00:00",
        "deadline": "2030-12-31T23:59:00",
        "application_reminder_sent": False,
        "reminder_date": "2030-12-01T09:00:00",
        "assessment_deadline": "2030-12-31T23:59:00",
        "prospectus": "https://en.wikipedia.org/wiki/Crash_test_dummy",
        "privacy_notice": "https://mhclgdigital.atlassian.net/wiki/home",
        "contact_email": "FundingService@communities.gov.uk",
        "instructions_json": {
            "en": "<p class='govuk-body'>This is the comprehensive dummy round for E2E testing.</p>",
            "cy": None,
        },
        "feedback_link": "https://mhclgdigital.atlassian.net/jira",
        "project_name_field_id": "projectName",
        "application_guidance_json": {
            "en": "<p class='govuk-body'>This is a fake fund for testing.</p>",
            "cy": None,
        },
        "guidance_url": "https://mhclgdigital.atlassian.net/wiki/home",
        "all_uploaded_documents_section_available": True,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": "true",
            "has_section_feedback": "true",
            "has_research_survey": "false",
            "is_feedback_survey_optional": "true",
            "is_section_feedback_optional": "true",
            "is_research_survey_optional": "false",
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Crash Round 2", "cy": None},
    },
    "base_path": 1140,
}
