LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Before you start", "cy": ""},
            "tree_path": "1064.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Name your application", "cy": ""},
            "tree_path": "1064.1.1.1",
            "form_name_json": {"en": "dpif-r4-name-your-application", "cy": ""},
        },
        {
            "section_name": {"en": "2. About your organisation", "cy": ""},
            "tree_path": "1064.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Organisation information", "cy": ""},
            "tree_path": "1064.1.2.1",
            "form_name_json": {"en": "dpif-r4-organisation-information", "cy": ""},
        },
        {
            "section_name": {"en": "3. Your skills and experience", "cy": ""},
            "tree_path": "1064.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Your skills and experience", "cy": ""},
            "tree_path": "1064.1.3.1",
            "form_name_json": {"en": "dpif-r4-your-skills-and-experience", "cy": ""},
        },
        {
            "section_name": {"en": "3.2 Roles and recruitment", "cy": ""},
            "tree_path": "1064.1.3.2",
            "form_name_json": {"en": "dpif-r4-roles-and-recruitment", "cy": ""},
        },
        {
            "section_name": {"en": "4. About your project", "cy": ""},
            "tree_path": "1064.1.4",
            "requires_feedback": None,
        },
        {
            "section_name": {
                "en": "4.1 Engaging the ODP (Open Digital Planning) community",
                "cy": "",
            },
            "tree_path": "1064.1.4.1",
            "form_name_json": {
                "en": "dpif-r4-engaging-the-odp-(open-digital-planning)-community",
                "cy": "",
            },
        },
        {
            "section_name": {"en": "4.2 Engaging the organisation", "cy": ""},
            "tree_path": "1064.1.4.2",
            "form_name_json": {"en": "dpif-r4-engaging-the-organisation", "cy": ""},
        },
        {
            "section_name": {"en": "4.3 Dataset information", "cy": ""},
            "tree_path": "1064.1.4.3",
            "form_name_json": {"en": "dpif-r4-dataset-information", "cy": ""},
        },
        {
            "section_name": {"en": "5. Future work", "cy": ""},
            "tree_path": "1064.1.5",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "5.1 Future work", "cy": ""},
            "tree_path": "1064.1.5.1",
            "form_name_json": {"en": "dpif-r4-future-work", "cy": ""},
        },
        {
            "section_name": {"en": "6. Declarations", "cy": ""},
            "tree_path": "1064.1.6",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "6.1 Declarations", "cy": ""},
            "tree_path": "1064.1.6.1",
            "form_name_json": {"en": "dpif-r4-declarations", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "f493d512-5eb4-11ee-8c99-0242ac120002",
        "short_name": "DPIF",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2022-09-11723",
        "funding_type": "UNCOMPETED",
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "name_json": {"en": "Digital Planning Improvement Fund", "cy": ""},
        "title_json": {
            "en": "funding to begin your digital planning improvement journey",
            "cy": "",
        },
        "description_json": {
            "en": "The Digital Planning Improvement Fund will provide local planning authorities with the funding and support to adopt modern planning practices within planning data, digital capabilities and development management software.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "83d49d14-ced1-4610-a3f5-36b432364b43",
        "fund_id": "f493d512-5eb4-11ee-8c99-0242ac120002",
        "short_name": "R4",
        "opens": "2025-07-29T12:00:00",
        "assessment_start": "2025-06-27T09:00:00",
        "deadline": "2025-10-30T12:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-10-23T09:00:00",
        "assessment_deadline": "2026-02-27T17:00:00",
        "prospectus": "https://www.localdigital.gov.uk/digital-planning/digital-planning-improvement-fund-2025-2026/",
        "privacy_notice": "https://www.gov.uk/guidance/digital-planning-improvement-fund-privacy-notice",
        "contact_email": "digitalplanningteam@communities.gov.uk",
        "instructions_json": {
            "en": "<p class='govuk-body'>We have been accepting applications continuously and formally reviewing them in batches.<br><br>Applications submitted by 29 July 2025 at midday are being considered for our first cohort.<br><br>You can submit your application by midday on 30 October 2025 to be considered for our next cohort, with onboarding starting in February 2026.<br><br>This approach allows us to provide high-quality support, by onboarding councils in coordinated groups.<br><br>While this is not a competitive funding process, we will ask questions to assess your readiness to receive the funding and begin the work.</p>",
            "cy": None,
        },
        "feedback_link": "",
        "project_name_field_id": "JAAhRP",
        "application_guidance_json": {
            "en": "<h2 class='govuk-heading govuk-heading-s'>What we'll ask you for</h2> <p class='govuk-body'>We have outlined the information needed to complete the application form on the <a class='govuk-link' target='_blank' href='https://www.localdigital.gov.uk/digital-planning/digital-planning-improvement-fund-2025-2026/'>Local Digital website</a>. If you have any questions, <a class='govuk-link' target='_blank' href='https://forms.office.com/pages/responsepage.aspx?id=EGg0v32c3kOociSi7zmVqAS7-pxIZO9CiW5a8c0IzZFUNVlFUzQ2NVNVSDRHQVRaNTExMENCNlU0Uy4u&route=shorturl'>sign up for our Q&A</a> on 9 July 2025 or contact digitalplanningteam@communities.gov.uk</p> <p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p>",
            "cy": None,
        },
        "guidance_url": "https://docs.google.com/document/d/1cF5eKphoBWEUe0Zv5HBwv0R3n1svCk16kUFRJhKnIQY",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Round 4", "cy": None},
    },
    "base_path": 1064,
}
