LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Your organisation", "cy": ""},
            "tree_path": "1074.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Your organisation", "cy": ""},
            "tree_path": "1074.1.1.1",
            "form_name_json": {"en": "ehcf-apply-your-organisation", "cy": ""},
        },
        {
            "section_name": {"en": "2. Skills and experience", "cy": ""},
            "tree_path": "1074.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Skills and experience", "cy": ""},
            "tree_path": "1074.1.2.1",
            "form_name_json": {"en": "ehcf-apply-skills-and-experience", "cy": ""},
        },
        {
            "section_name": {"en": "3. Proposal", "cy": ""},
            "tree_path": "1074.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Proposal", "cy": ""},
            "tree_path": "1074.1.3.1",
            "form_name_json": {"en": "ehcf-apply-proposal", "cy": ""},
        },
        {
            "section_name": {"en": "4. Deliverability and risks", "cy": ""},
            "tree_path": "1074.1.4",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "4.1 Deliverability and risks", "cy": ""},
            "tree_path": "1074.1.4.1",
            "form_name_json": {"en": "ehcf-apply-deliverability-and-risks", "cy": ""},
        },
        {
            "section_name": {"en": "5. Cost and value for money", "cy": ""},
            "tree_path": "1074.1.5",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "5.1 Cost and value for money", "cy": ""},
            "tree_path": "1074.1.5.1",
            "form_name_json": {"en": "ehcf-apply-cost-and-value-for-money", "cy": ""},
        },
        {
            "section_name": {"en": "6. Outcomes and measuring impact", "cy": ""},
            "tree_path": "1074.1.6",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "6.1 Outcomes and measuring impact", "cy": ""},
            "tree_path": "1074.1.6.1",
            "form_name_json": {"en": "ehcf-apply-outcomes-and-measuring-impact", "cy": ""},
        },
        {
            "section_name": {"en": "7. Letter of support and declaration", "cy": ""},
            "tree_path": "1074.1.7",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "7.1 Letter of support and declaration", "cy": ""},
            "tree_path": "1074.1.7.1",
            "form_name_json": {"en": "ehcf-apply-declaration", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "01f3a07a-1ea8-46d2-9286-d6bf06f4a831",
        "short_name": "EHCF",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2025-12-17297",
        "funding_type": "COMPETITIVE",
        "owner_organisation_name": "",
        "owner_organisation_shortname": "",
        "owner_organisation_logo_uri": "",
        "name_json": {"en": "Ending Homelessness in Communities Fund", "cy": ""},
        "title_json": {"en": "funding to end homelessness in communities", "cy": ""},
        "description_json": {
            "en": "This fund will help voluntary, community and faith sector organisations reduce homelessness, transform existing day support offers, support individuals to live independently and prevent them from returning to rough sleeping.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "e3a99e8c-e5ef-4d40-844d-38e27bf4042f",
        "fund_id": "01f3a07a-1ea8-46d2-9286-d6bf06f4a831",
        "short_name": "APPLY",
        "opens": "2026-02-23T12:00:00",
        "assessment_start": "2026-04-07T12:00:00",
        "deadline": "2026-03-31T12:00:00",
        "reminder_date": "2026-03-23T12:00:00",
        "assessment_deadline": "2026-06-30T12:00:00",
        "prospectus": "https://www.gov.uk/guidance/ending-homelessness-in-communities-fund-prospectus",
        "privacy_notice": "",
        "contact_email": "",
        "instructions_json": {"en": None, "cy": None},
        "feedback_link": "",
        "project_name_field_id": "WwxTJv",
        "application_guidance_json": {
            "en": "<p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p>",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": True,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": True},
        "send_incomplete_application_emails": True,
        "title_json": {"en": "Application", "cy": None},
    },
    "base_path": 1074,
}
