LOADER_CONFIG = {
    "sections_config": [
        {"section_name": {"en": "1. Local authority", "cy": ""}, "tree_path": "1068.1.1", "requires_feedback": None},
        {
            "section_name": {"en": "1.1 Local authority details", "cy": ""},
            "tree_path": "1068.1.1.1",
            "form_name_json": {"en": "lahf-lahftu-local-authority-details", "cy": ""},
        },
        {
            "section_name": {"en": "1.2 Occupational therapy report", "cy": ""},
            "tree_path": "1068.1.1.2",
            "form_name_json": {"en": "lahf-lahftu-occupational-therapy-report", "cy": ""},
        },
        {
            "section_name": {"en": "2. Property and adaptation requirements", "cy": ""},
            "tree_path": "1068.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Property details", "cy": ""},
            "tree_path": "1068.1.2.1",
            "form_name_json": {"en": "lahf-lahftu-property-details", "cy": ""},
        },
        {
            "section_name": {"en": "2.2 Adaptation requirements", "cy": ""},
            "tree_path": "1068.1.2.2",
            "form_name_json": {"en": "lahf-lahftu-adaptation-requirements", "cy": ""},
        },
        {"section_name": {"en": "3. Key dates", "cy": ""}, "tree_path": "1068.1.3", "requires_feedback": None},
        {
            "section_name": {"en": "3.1 Key dates", "cy": ""},
            "tree_path": "1068.1.3.1",
            "form_name_json": {"en": "lahf-lahftu-key-dates", "cy": ""},
        },
        {
            "section_name": {"en": "4. Additional information (optional)", "cy": ""},
            "tree_path": "1068.1.4",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "4.1 Additional information", "cy": ""},
            "tree_path": "1068.1.4.1",
            "form_name_json": {"en": "lahf-lahftu-additional-information", "cy": ""},
        },
        {"section_name": {"en": "5. Declarations", "cy": ""}, "tree_path": "1068.1.5", "requires_feedback": None},
        {
            "section_name": {"en": "5.1 Declarations", "cy": ""},
            "tree_path": "1068.1.5.1",
            "form_name_json": {"en": "lahf-lahftu-declarations", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "28c2f175-eda1-4ba6-9337-e05150708155",
        "short_name": "LAHF",
        "welsh_available": False,
        "ggis_scheme_reference_number": "",
        "funding_type": "COMPETITIVE",
        "owner_organisation_name": None,
        "owner_organisation_shortname": None,
        "owner_organisation_logo_uri": None,
        "name_json": {"en": "Local Authority Housing Fund", "cy": ""},
        "title_json": {"en": "funding to deliver adapted and accessible homes", "cy": ""},
        "description_json": {
            "en": "The £1.2 billion Local Authority Housing Fund (LAHF) is an innovative capital fund that supports local authorities in England to obtain housing for those who are unable to find settled accommodation on resettlement schemes.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "6bb128c7-3ae9-4192-bee4-99b6b5b3b98f",
        "fund_id": "28c2f175-eda1-4ba6-9337-e05150708155",
        "short_name": "LAHFtu",
        "opens": "2025-09-24T12:00:00",
        "assessment_start": "2025-09-24T12:00:00",
        "deadline": "2026-03-06T12:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2026-02-27T12:00:00",
        "assessment_deadline": "2026-03-20T12:00:00",
        "prospectus": "https://www.gov.uk/government/collections/local-authority-housing-fund",
        "privacy_notice": "https://www.not-available.com",
        "contact_email": "LAHFResettlementTopUps@Communities.gov.uk",
        "instructions_json": {
            "en": "Read the <a href='/assets/documents/lahf/LAHF-Top-Ups-Fund-Guidance.pdf' target='_blank' class='govuk-link'>Local Authority Housing Fund top-up guidance (opens in new tab)</a> before you apply.",
            "cy": None,
        },
        "feedback_link": "",
        "project_name_field_id": "svIchm",
        "application_guidance_json": {
            "en": "<p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p>",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": True,
        },
        "eligibility_config": {"has_eligibility": True},
        "title_json": {"en": "Resettlement top-up", "cy": None},
    },
    "base_path": 1068,
}
