LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Organisation details", "cy": ""},
            "tree_path": "1070.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Organisation details", "cy": ""},
            "tree_path": "1070.1.1.1",
            "form_name_json": {"en": "nwp-r1-organisation-details", "cy": ""},
        },
        {
            "section_name": {"en": "2. Applicant information", "cy": ""},
            "tree_path": "1070.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Applicant information", "cy": ""},
            "tree_path": "1070.1.2.1",
            "form_name_json": {"en": "nwp-r1-applicant-information", "cy": ""},
        },
        {"section_name": {"en": "3. Proposal", "cy": ""}, "tree_path": "1070.1.3", "requires_feedback": None},
        {
            "section_name": {"en": "3.1 Proposal", "cy": ""},
            "tree_path": "1070.1.3.1",
            "form_name_json": {"en": "nwp-r1-proposal", "cy": ""},
        },
        {"section_name": {"en": "4. Risks", "cy": ""}, "tree_path": "1070.1.4", "requires_feedback": None},
        {
            "section_name": {"en": "4.1 Risk", "cy": ""},
            "tree_path": "1070.1.4.1",
            "form_name_json": {"en": "nwp-r1-risk", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "44676f65-616d-4819-af7a-a457f693f008",
        "short_name": "NWP",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2025-10-17200",
        "funding_type": "COMPETITIVE",
        "owner_organisation_name": "",
        "owner_organisation_shortname": "",
        "owner_organisation_logo_uri": "",
        "name_json": {"en": "National Workforce Programme", "cy": ""},
        "title_json": {
            "en": "funding to develop the expertise, skills and capacity of the frontline homeless workforce",
            "cy": "",
        },
        "description_json": {
            "en": "A national workforce programme to help the frontline homeless workforce in England to develop expertise, skills and capacity. ",
            "cy": "",
        },
    },
    "round_config": {
        "id": "e87283ae-e514-4a5e-bcaa-b32526fad721",
        "fund_id": "44676f65-616d-4819-af7a-a457f693f008",
        "short_name": "R1",
        # "opens": "2025-11-03T12:00:00",
        "opens": "2025-10-03T12:00:00",
        "assessment_start": "2025-12-02T12:00:00",
        "deadline": "2025-12-01T12:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-11-24T12:00:00",
        "assessment_deadline": "2026-01-20T12:00:00",
        "prospectus": "www.notgotityet.com",
        "privacy_notice": "www.notgotityet.com",
        "contact_email": "",
        "instructions_json": {"en": None, "cy": None},
        "feedback_link": "",
        "project_name_field_id": "TBC",
        "application_guidance_json": {
            "en": "<p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p>",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": True,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": True,
        },
        "eligibility_config": {"has_eligibility": True},
        "title_json": {"en": "Round 1", "cy": None},
    },
    "base_path": 1070,
}
