LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Place and secondary contact information", "cy": ""},
            "tree_path": "1063.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Place and secondary contact information", "cy": ""},
            "tree_path": "1063.1.1.1",
            "form_name_json": {"en": "pfn-rp-place-and-secondary-contact-information", "cy": ""},
        },
        {
            "section_name": {"en": "2. Community engagement", "cy": ""},
            "tree_path": "1063.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Community engagement and support", "cy": ""},
            "tree_path": "1063.1.2.1",
            "form_name_json": {"en": "pfn-rp-community-engagement-and-support", "cy": ""},
        },
        {
            "section_name": {"en": "3. Your Regeneration Plan", "cy": ""},
            "tree_path": "1063.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 10-year vision", "cy": ""},
            "tree_path": "1063.1.3.1",
            "form_name_json": {"en": "pfn-rp-10-year-vision", "cy": ""},
        },
        {
            "section_name": {"en": "3.2 4-year investment plan: key priorities", "cy": ""},
            "tree_path": "1063.1.3.2",
            "form_name_json": {"en": "pfn-rp-4-year-investment-plan-key-priorities", "cy": ""},
        },
        {
            "section_name": {"en": "3.3 4-year investment plan: interventions", "cy": ""},
            "tree_path": "1063.1.3.3",
            "form_name_json": {"en": "pfn-rp-4-year-investment-plan-interventions", "cy": ""},
        },
        {
            "section_name": {"en": "4. Payment profile and spend", "cy": ""},
            "tree_path": "1063.1.4",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "4.1 Payment profile and spend forecast", "cy": ""},
            "tree_path": "1063.1.4.1",
            "form_name_json": {"en": "pfn-rp-payment-profile-and-spend-forecast", "cy": ""},
        },
        {
            "section_name": {"en": "4.2 Projects", "cy": ""},
            "tree_path": "1063.1.4.2",
            "form_name_json": {"en": "pfn-rp-projects", "cy": ""},
        },
        {
            "section_name": {"en": "4.3 Capacity funding", "cy": ""},
            "tree_path": "1063.1.4.3",
            "form_name_json": {"en": "pfn-rp-capacity-funding", "cy": ""},
        },
        {
            "section_name": {"en": "4.4 Management costs", "cy": ""},
            "tree_path": "1063.1.4.4",
            "form_name_json": {"en": "pfn-rp-management-costs", "cy": ""},
        },
        {"section_name": {"en": "5. Programme delivery", "cy": ""}, "tree_path": "1063.1.5", "requires_feedback": None},
        {
            "section_name": {"en": "5.1 Milestones", "cy": ""},
            "tree_path": "1063.1.5.1",
            "form_name_json": {"en": "pfn-rp-milestones", "cy": ""},
        },
        {
            "section_name": {"en": "5.2 Management of funds", "cy": ""},
            "tree_path": "1063.1.5.2",
            "form_name_json": {"en": "pfn-rp-management-of-funds", "cy": ""},
        },
        {
            "section_name": {"en": "5.3 Available resources and skills", "cy": ""},
            "tree_path": "1063.1.5.3",
            "form_name_json": {"en": "pfn-rp-available-resources-and-skills", "cy": ""},
        },
        {
            "section_name": {"en": "5.4 Additional support", "cy": ""},
            "tree_path": "1063.1.5.4",
            "form_name_json": {"en": "pfn-rp-additional-support", "cy": ""},
        },
        {"section_name": {"en": "6. Declarations", "cy": ""}, "tree_path": "1063.1.6", "requires_feedback": None},
        {
            "section_name": {"en": "6.1 Declarations", "cy": ""},
            "tree_path": "1063.1.6.1",
            "form_name_json": {"en": "pfn-rp-declarations", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "26e831c1-8ae7-4f62-b230-6f409e2700fa",
        "short_name": "PFN",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2024-01-13314",
        "funding_type": "UNCOMPETED",
        "owner_organisation_name": "",
        "owner_organisation_shortname": "",
        "owner_organisation_logo_uri": "",
        "name_json": {"en": "Plan for Neighbourhoods", "cy": ""},
        "title_json": {"en": "Submit your Regeneration Plan for the Plan for Neighbourhoods programme", "cy": ""},
        "description_json": {
            "en": "A £1.5 billion programme to invest in 75 areas over the next decade – a long-term strategy to fix the foundations of those places most left behind.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "9217792e-d8c2-45c8-8170-eed4a8946184",
        "fund_id": "26e831c1-8ae7-4f62-b230-6f409e2700fa",
        "short_name": "RP",
        "opens": "2025-06-16T09:00:00",
        "assessment_start": "2025-07-07T09:00:00",
        "deadline": "2025-11-28T23:59:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-11-28T09:00:00",
        "assessment_deadline": "2025-12-30T23:59:00",
        "prospectus": "https://www.gov.uk/government/publications/plan-for-neighbourhoods-prospectus-and-tools/plan-for-neighbourhoods-prospectus",
        "privacy_notice": "https://www.gov.uk/government/publications/plan-for-neighbourhoods-regeneration-plan-guidance/plan-for-neighbourhoods-privacy-notice-for-regeneration-plan-submissions-form",
        "contact_email": "PfNcorrespondence@communities.gov.uk",
        "instructions_json": {
            "en": "You must complete this form to submit your Regeneration Plan for the Plan for Neighbourhoods programme. <br><br>\r\n\r\nMake sure you have read the accompanying guidance before you start:\r\n<ul>\r\n<li> <a href='https://www.gov.uk/government/publications/plan-for-neighbourhoods-prospectus-and-tools/plan-for-neighbourhoods-prospectus'>prospectus</a></li>\r\n<li><a href='https://www.gov.uk/government/publications/plan-for-neighbourhoods-neighbourhood-boards-and-place-boundaries/plan-for-neighbourhoods-governance-and-boundary-guidance'>governance and boundary guidance</a></li>\r\n<li><a href='https://www.gov.uk/government/publications/plan-for-neighbourhoods-prospectus-and-tools/plan-for-neighbourhoods-pre-approved-interventions'>pre-approved interventions</a></li>\r\n<li><a href='https://www.gov.uk/government/publications/plan-for-neighbourhoods-prospectus-and-tools/plan-for-neighbourhoods-list-of-powers'>list of powers</a></li>\r\n</ul>",
            "cy": None,
        },
        "feedback_link": "",
        "project_name_field_id": "UNlQWk",
        "application_guidance_json": {
            "en": "<h2 class='govuk-heading govuk-heading-s'>What this process involves</h2>\r\n\r\nAll 75 places included in the Plan for Neighbourhoods programme must submit their Regeneration Plan to the Ministry of Housing, Communities and Local Government (MHCLG) using this form. Submitting your plan is the next step before programme delivery funding is released.<br><br> \r\n\r\nIt should be completed by the nominated representative for each place. <br><br> \r\n\r\nAll information submitted must have been approved by the Neighbourhood Board and through any local approval process required by the accountable body. <br><br> \r\n\r\nWhere this form is not complete, or we require further information or clarification, you will receive an email notifying you to make any updates and changes as appropriate.<br><br> \r\n\r\nThe information in the form will be used to validate the readiness of local areas to receive funding and deliver in line with the programme's prospectus and published guidance. <br><br> \r\n\r\nRead our <a href='https://www.gov.uk/government/publications/plan-for-neighbourhoods-regeneration-plan-guidance/plan-for-neighbourhoods-privacy-notice-for-regeneration-plan-submissions-form'>privacy notice</a> for more information.\r\n\r\n<h2 class='govuk-heading govuk-heading-s'>What we'll ask you for</h2> <p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Regeneration Plan", "cy": None},
    },
    "base_path": 1063,
}
