LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Organisation information", "cy": ""},
            "tree_path": "1069.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Organisation information", "cy": ""},
            "tree_path": "1069.1.1.1",
            "form_name_json": {"en": "shif-apply-organisation-information", "cy": ""},
        },
        {
            "section_name": {"en": "2. Your proposal", "cy": ""},
            "tree_path": "1069.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Your proposal", "cy": ""},
            "tree_path": "1069.1.2.1",
            "form_name_json": {"en": "shif-apply-your-proposal", "cy": ""},
        },
        {
            "section_name": {"en": "3. Co-production with tenants", "cy": ""},
            "tree_path": "1069.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Co-production with tenants", "cy": ""},
            "tree_path": "1069.1.3.1",
            "form_name_json": {"en": "shif-apply-co-production-with-tenants", "cy": ""},
        },
        {
            "section_name": {"en": "4. Innovation and scalability", "cy": ""},
            "tree_path": "1069.1.4",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "4.1 Innovation and scalability", "cy": ""},
            "tree_path": "1069.1.4.1",
            "form_name_json": {"en": "shif-apply-innovation-and-scalability", "cy": ""},
        },
        {
            "section_name": {
                "en": "5. Costs, value for money and risk management",
                "cy": "",
            },
            "tree_path": "1069.1.5",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "5.1 Costs and value for money", "cy": ""},
            "tree_path": "1069.1.5.1",
            "form_name_json": {"en": "shif-apply-costs-and-value-for-money", "cy": ""},
        },
        {
            "section_name": {"en": "5.2 Risk management", "cy": ""},
            "tree_path": "1069.1.5.2",
            "form_name_json": {"en": "shif-apply-risk-management", "cy": ""},
        },
        {
            "section_name": {"en": "6. Outcomes and measuring impact", "cy": ""},
            "tree_path": "1069.1.6",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "6.1 Outcomes and measuring impact", "cy": ""},
            "tree_path": "1069.1.6.1",
            "form_name_json": {"en": "shif-apply-outcomes-and-measuring-impact", "cy": ""},
        },
        {
            "section_name": {"en": "7. Declarations", "cy": ""},
            "tree_path": "1069.1.7",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "7.1 Declarations", "cy": ""},
            "tree_path": "1069.1.7.1",
            "form_name_json": {"en": "shif-apply-declarations", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "217e185c-3bb9-4bd0-b210-fd8a70e0806f",
        "short_name": "SHIF",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2025-07-16559",
        "funding_type": "COMPETITIVE",
        "owner_organisation_name": None,
        "owner_organisation_shortname": None,
        "owner_organisation_logo_uri": None,
        "name_json": {"en": "Social Housing Innovation Fund", "cy": ""},
        "title_json": {
            "en": "funding to strengthen social housing tenants’ voices",
            "cy": "",
        },
        "description_json": {
            "en": "Improving the quality of social housing and strengthening ‘tenant voice’ are key ambitions for this government. Strengthening tenant voice means creating meaningful opportunities for tenants to share their ideas and tell their landlords what they think about how their homes are managed. It also means that landlords listen to tenants’ views and make changes based on what their tenants think.   ",
            "cy": "",
        },
    },
    "round_config": {
        "id": "798ec042-1f64-4714-bde9-98bef1cb067c",
        "fund_id": "217e185c-3bb9-4bd0-b210-fd8a70e0806f",
        "short_name": "APPLY",
        "opens": "2025-10-27T12:00:00",
        "assessment_start": "2026-01-09T12:00:00",
        "deadline": "2026-01-09T12:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2026-01-05T12:00:00",
        "assessment_deadline": "2026-02-09T12:00:00",
        "prospectus": "https://www.gov.uk/government/publications/social-housing-innovation-fund-prospectus",
        "privacy_notice": "https://www.gov.uk/government/publications/social-housing-innovation-fund-prospectus/social-housing-innovation-fund-privacy-notice",
        "contact_email": "socialhousinginnovationfund@communities.gov.uk",
        "instructions_json": {
            "en": "",
            "cy": None,
        },
        "feedback_link": "",
        "project_name_field_id": "oEoIjK",
        "application_guidance_json": {
            "en": "<p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p>",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": True},
        "title_json": {"en": "Application", "cy": None},
    },
    "base_path": 1069,
}
